import { createClient } from '@supabase/supabase-js';
import { access, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const url = process.env.PUBLIC_SUPABASE_URL;
const key = process.env.PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const targetDirectory = path.resolve('src/content/blog');
const marker = '<!-- Generated by scripts/sync-blog.mjs. Edit in /admin/, not in this file. -->';

if (!url || !key || url.includes('SEU-PROJETO') || key.includes('SUBSTITUA_AQUI')) {
  console.log('[sync:blog] Supabase não configurado; mantendo os artigos locais.');
  process.exit(0);
}

const supabase = createClient(url, key, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const { data: posts, error } = await supabase
  .from('blog_posts')
  .select('slug,title,description,author,category,tags,cover_image,cover_alt,featured,seo_title,seo_description,published_at,updated_at,body_markdown')
  .eq('status', 'published')
  .lte('published_at', new Date().toISOString())
  .order('published_at', { ascending: false });

if (error) throw new Error(`[sync:blog] Falha ao consultar artigos: ${error.message}`);

for (const post of posts ?? []) {
  const filePath = path.join(targetDirectory, `${post.slug}.md`);

  try {
    await access(filePath);
    const current = await readFile(filePath, 'utf8');
    if (!current.includes(marker)) {
      console.warn(`[sync:blog] Ignorado “${post.slug}”: existe um artigo local com o mesmo slug.`);
      continue;
    }
  } catch {
    // O arquivo ainda não existe; será criado abaixo.
  }

  const frontmatter = [
    '---',
    `title: ${JSON.stringify(post.title)}`,
    `description: ${JSON.stringify(post.description)}`,
    `publishedAt: ${JSON.stringify(post.published_at)}`,
    `updatedAt: ${JSON.stringify(post.updated_at)}`,
    `author: ${JSON.stringify(post.author)}`,
    `category: ${JSON.stringify(post.category)}`,
    `tags: ${JSON.stringify(post.tags ?? [])}`,
    `coverImage: ${JSON.stringify(post.cover_image)}`,
    `coverAlt: ${JSON.stringify(post.cover_alt)}`,
    `featured: ${Boolean(post.featured)}`,
    'draft: false',
    ...(post.seo_title ? [`seoTitle: ${JSON.stringify(post.seo_title)}`] : []),
    ...(post.seo_description ? [`seoDescription: ${JSON.stringify(post.seo_description)}`] : []),
    '---',
    marker,
    '',
    post.body_markdown.trim(),
    '',
  ].join('\n');

  await writeFile(filePath, frontmatter, 'utf8');
}

console.log(`[sync:blog] ${posts?.length ?? 0} artigo(s) publicado(s) sincronizado(s).`);
