import { createClient } from '@supabase/supabase-js';
import { access, mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { getEditorialFeedback } from '../src/lib/editorial.mjs';

// Astro reads .env later, but this script runs before Astro starts.
try {
  process.loadEnvFile('.env');
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}

const url = process.env.PUBLIC_SUPABASE_URL;
const key = process.env.PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const targetDirectory = path.resolve('src/content/blog');
const marker = '<!-- Generated by scripts/sync-blog.mjs. Edit in /admin/, not in this file. -->';

if (!url || !key || url.includes('SEU-PROJETO') || key.includes('SUBSTITUA_AQUI')) {
  console.log('[sync:blog] Supabase não configurado; mantendo os artigos locais.');
  process.exit(0);
}

const supabase = createClient(url, key, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const { data: posts, error } = await supabase
  .from('blog_posts')
  .select('slug,title,description,author,category,tags,cover_image,cover_alt,featured,seo_title,seo_description,canonical_url,published_at,updated_at,body_markdown')
  .eq('status', 'published')
  .lte('published_at', new Date().toISOString())
  .order('published_at', { ascending: false });

if (error) throw new Error(`[sync:blog] Falha ao consultar artigos: ${error.message}`);

// Validate the whole response before touching files: a bad article must fail
// the build rather than publish unsafe HTML or remove valid generated pages.
for (const post of posts ?? []) {
  const feedback = getEditorialFeedback({
    title: post.title, slug: post.slug, description: post.description,
    body: post.body_markdown, author: post.author, coverImage: post.cover_image,
    coverAlt: post.cover_alt, seoTitle: post.seo_title ?? '',
    seoDescription: post.seo_description ?? '', canonicalUrl: post.canonical_url ?? '',
    publishing: true,
  });
  if (feedback.errors.length) throw new Error(`[sync:blog] Artigo “${post.slug}” inválido: ${feedback.errors.join(' ')}`);
}

await mkdir(targetDirectory, { recursive: true });
const publishedSlugs = new Set();

for (const post of posts ?? []) {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(post.slug)) {
    console.warn(`[sync:blog] Ignorado slug inválido recebido do CMS: “${post.slug}”.`);
    continue;
  }

  publishedSlugs.add(post.slug);
  const filePath = path.join(targetDirectory, `${post.slug}.md`);

  try {
    await access(filePath);
    const current = await readFile(filePath, 'utf8');
    if (!current.includes(marker)) {
      console.warn(`[sync:blog] Ignorado “${post.slug}”: existe um artigo local com o mesmo slug.`);
      continue;
    }
  } catch {
    // O arquivo ainda não existe; será criado abaixo.
  }

  const frontmatter = [
    '---',
    `title: ${JSON.stringify(post.title)}`,
    `description: ${JSON.stringify(post.description)}`,
    `publishedAt: ${JSON.stringify(post.published_at)}`,
    `updatedAt: ${JSON.stringify(post.updated_at)}`,
    `author: ${JSON.stringify(post.author)}`,
    `category: ${JSON.stringify(post.category)}`,
    `tags: ${JSON.stringify(post.tags ?? [])}`,
    `coverImage: ${JSON.stringify(post.cover_image)}`,
    `coverAlt: ${JSON.stringify(post.cover_alt)}`,
    `featured: ${Boolean(post.featured)}`,
    'draft: false',
    ...(post.seo_title ? [`seoTitle: ${JSON.stringify(post.seo_title)}`] : []),
    ...(post.seo_description ? [`seoDescription: ${JSON.stringify(post.seo_description)}`] : []),
    ...(post.canonical_url ? [`canonicalUrl: ${JSON.stringify(post.canonical_url)}`] : []),
    '---',
    marker,
    '',
    post.body_markdown.trim(),
    '',
  ].join('\n');

  await writeFile(filePath, frontmatter, 'utf8');
}

/* Remove somente arquivos comprovadamente gerados por este script. Isso evita
   que um artigo excluído, arquivado ou despublicado no CMS continue entrando
   no build e sendo rastreado pelos buscadores. Artigos editoriais locais nunca
   são removidos. */
let removedCount = 0;
for (const entry of await readdir(targetDirectory, { withFileTypes: true })) {
  if (!entry.isFile() || !/\.mdx?$/i.test(entry.name)) continue;

  const slug = entry.name.replace(/\.mdx?$/i, '');
  if (publishedSlugs.has(slug)) continue;

  const filePath = path.join(targetDirectory, entry.name);
  const current = await readFile(filePath, 'utf8');
  if (!current.includes(marker)) continue;

  await unlink(filePath);
  removedCount += 1;
}

console.log(
  `[sync:blog] ${publishedSlugs.size} artigo(s) publicado(s) sincronizado(s); ${removedCount} arquivo(s) obsoleto(s) removido(s).`,
);
